### ISSUE TITLE
evap trend :: code rerun 

### ISSUE THREAD

**Issue by Jorub** [imarkonis/ithaca#157]
Rerun evap trend code

**Comment by MiRoVaGo** [comment]
Why is there 03_c_<> and 03_c_v2_<>?
The 03_m_map_ipcc_hexagon_uncertainty.R script need tidying up
The 03_map_coverage.R script doesn't follow naming convention of the rest of the scripts
In 03_<> scripts it would be best to do pxx <- ggplot(...); ggsave(plot = pxx, ...) to guarantee the right plot is being saved
Below see specific warning/error messages
---
01_d_global_grid_calculate_dci_uncertainty_per_grid.R
Warning message:
In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 1
---
01_e_global_grid_calculate_uncertainty_per_grid_dataset_contribution.R
Warning message:
In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 1
---
01_g_global_trend_correlation.R (when sourcing)
Error in Math.data.frame(x = list(fldas = c(0, 1.09210179987872e-169,  : 
  non-numeric-alike variable(s) in data frame: rn
In addition: Warning message:
In melt.data.table(as.data.table(cor_data, keep.rownames = T)) :
  id.vars and measure.vars are internally guessed when both are 'NULL'. All non-numeric/integer/logical type columns are considered id.vars, which in this case are columns [rn, ...]. Consider providing at least one of 'id' or 'measure' vars in future.
---
02_a_masks_cumulative_trend_direction.R
Warning message:
In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 2
---
02_b_masks_mean_slopes.R
Warning message:
In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 1
---
02_g_masks_correlation.R
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In melt.data.table(as.data.table(cor(dcast(.SD, formula = lon +  ... :
  id.vars and measure.vars are internally guessed when both are 'NULL'. All non-numeric/integer/logical type columns are considered id.vars, which in this case are columns [rn, ...]. Consider providing at least one of 'id' or 'measure' vars in future.
---
03_c_plot_mean_slopes_masks_by_product.R
10 Warning messages:
`geom_abline()`: Ignoring `mapping` because `slope` and/or `intercept` were provided. 
---
03_c_v2_plot_mean_slopes_masks_by_product.R
10 Warning messages:
`geom_abline()`: Ignoring `mapping` because `slope` and/or `intercept` were provided. 
---
03_j_plot_change_in_probability_groups_per_dataset_leftout.R
Warning messages:
1: Removed 1 row containing missing values or values outside the scale range (`geom_bar()`). 
2: Removed 76 rows containing missing values or values outside the scale range (`geom_bar()`). 
---

**Comment by Jorub** [comment]
Code checked
