### ISSUE TITLE
geo_functions :: Edit bug in brick_to_dt

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#171]
brick_to_dt function causes data loss.

**Comment by Jorub** [comment]
as.data.frame is the culprit here. 
A function called raster_to_dt was added to geo_functions that does not cause data loss. This new function raster_to_dt is essentially the same as calling pRecipe::tabular. Not that calling brick_to_dt and raster_to_dt also use parallelization differently. raster_to_dt already detects cores and operates in parallel.
